title: TechExcel Migrate SAP RISE to Azure
description: In this course, you will learn to configure a Copilot agent to answer natural language prompts based on an SAP data source.
theme: just-the-docs

aux_links:
  "Migrate SAP RISE to Azure":
    - "https://github.com/microsoft/TechExcel-Migrate-SAP-RISE-to-Azure/"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
